dist: trusty
sudo: false
# .travis.yml
language: node_js
install:
  - npm install
node_js:
  - "6.9.1"
  # keep the npm cache around to speed up installs
cache:
  directories:
    - "node_modules"
    - "$HOME/.npm"
addons:
  sonarcloud:
    organization: "merntask"
    token:
      secure: "4ec7c318240a9d4ba62549864283b7ad7c4159bb"

script:
  - "sonar-scanner"
